use_modular_headers!

target 'iOS-Example' do
  platform :ios, '10.0'

  pod 'LeakChecker', :path => '../'
end

target 'tvOS-Example' do
  platform :tvos, '10.0'

  pod 'LeakChecker', :path => '../'
end

target 'macOS-Example' do
  platform :osx, '10.13'

  pod 'LeakChecker', :path => '../'
end
